#!/bin/bash
# USAGE: share-ami.sh <packer_output_logfile>
# 
# The script takes a packer output logfile generated by `packer build -machine-readable Packerfile`
# and parses the AMI ids and shares with the account numbers in $AWS_ACCOUNTS

AWS_ACCOUNTS="111111111111 222222222222"
RC=0

# If you want to manually share AMI ids, you can set $AMIS env var
# which takes precedence over Packer output.
# Set AMIS env var in this format:
# AMIS="
#    region:ami-id
#    region:ami-id
# "
if [[ -n $AMIS ]]; then
  echo Found env var $AMIS. Setting inputs = "$AMIS"
else
  echo "Parsing $1 for AMIs"
  AMIS=`cat $1 | awk -F, '$0 ~/artifact,0,id/ {print $6}' | sed 's/%!(PACKER_COMMA)/\n/g'`
fi

for ami in $AMIS; do
  region=`echo $ami | awk -F: '{print $1}'`
  ami_id=`echo $ami | awk -F: '{print $2}'`
  for account in $AWS_ACCOUNTS; do
    echo "Sharing AMI $ami_id from region $region with AWS account $account..."
    aws ec2 modify-image-attribute --region=$region --image-id $ami_id --launch-permission "{\"Add\":[{\"UserId\":\"$account\"}]}" || RC=$?
  done
done

if [[ $RC == 0 ]]; then
  echo "Successfully shared `echo $AMIS` with accounts $AWS_ACCOUNTS"
else
  echo "Failed to share `echo $AMIS` with accounts $AWS_ACCOUNTS"
fi

exit $RC
