name 'jenkins-wrapper'
maintainer 'Huy Nguyen'
maintainer_email 'ace321@gmail.com'
license 'apachev2'
description 'Installs/Configures jenkins-wrapper'
long_description 'Installs/Configures jenkins-wrapper'
version '0.1.0'

depends 'jenkins', '~>2.6.0'
depends 'chef-client', '~>5.0.0'
depends 'git', '~>5.0.0'