#
# Cookbook Name:: jenkins-wrapper
# Recipe:: default
#
# Copyright 2016 Huy Nguyen
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

default['jenkins']['master'].tap do |master|
  master['install_method'] = 'war'
  master['source'] = 'http://mirrors.jenkins-ci.org/war-stable/1.651.3/jenkins.war'
  master['port'] = 8080
end

default['jenkins-wrapper']['plugins'] = %w( 
  build-flow-plugin token-macro github-api structs junit display-url-api mailer credentials
  ssh-credentials git-client script-security matrix-project rebuild workflow-step-api workflow-api 
  workflow-basic-steps node-iterator-api ssh-slaves vsphere-cloud token-macro config-file-provider 
  managed-scripts job-dsl project-inheritance javadoc maven-plugin script-security promoted-builds 
  mapdb-api scm-api workflow-scm-step subversion run-condition conditional-buildstep parameterized-trigger
  git github-api plain-credentials github bouncycastle-api ssh-agent ghprb saferestart
  )

default['jenkins-wrapper']['packer']['source_url'] = 'https://releases.hashicorp.com/packer/0.10.1/packer_0.10.1_linux_amd64.zip'

# Fill out your Github stuff below
default['jenkins-wrapper']['github']['user'] = 'user1'
default['jenkins-wrapper']['github']['admins'] = 'user1 user2'
default['jenkins-wrapper']['github']['repo'] = 'https://github.com/user1/packer-templates'
default['jenkins-wrapper']['github']['credential_id'] = '...'  ## generated by `uuidgen`
default['jenkins-wrapper']['github']['github_auth_id'] = '...'  ## generated by `uuidgen`
default['jenkins-wrapper']['github']['token_file'] = '/var/lib/jenkins/github_token'
